### ISSUE TITLE
License object is incorrectly requiring license url.

### ISSUE THREAD

**Issue by nesl247** [Mermade/openapi-lint-vscode#1]
According to https://swagger.io/specification/#licenseObject the `url` key is not required. However, the linting is saying my document is not valid without it.

**Comment by MikeRalphson** [comment]
That's one of the differences between validation (which enforces the spec) and linting, which is more stylistic. I could probably tweak the status message to make this clearer.

**Comment by nesl247** [comment]
I actually hadn't realized there were 2 separate actions (lint and validate). What style is this extension enforcing?

I think that's where the real confusion is coming into play. Since this is `openapi-lint`, I only expected it to validate according to the spec and nothing more, and thus didn't search for an action called `OpenAPI Validate`, I simply searched for `lint`.

**Comment by MikeRalphson** [comment]
The linter rules are similar to those of speccy (as the two projects share code): http://speccy.io/rules/

Thoughts on how to clarify things appreciated.

**Comment by nesl247** [comment]
I would probably update the README to clarify that there are two commands, and maybe copy

> Remember, linting is more than validaiton, so these rules will do more than simply make sure your files are valid. They'll make your specs better than valid, they'll make them useful.

Because I didn't know there were 2 commands, I assumed the linting was only making sure the document was valid.

**Comment by MikeRalphson** [comment]
README hopefully clarified to indicate there are two commands and to link to a definition of linting as opposed to validation. Thanks for the report.

**Comment by nesl247** [comment]
Looks perfect. Thanks so much!
