### ISSUE TITLE
Unable to get intellisense unless rename to oas2.yaml

### ISSUE THREAD

**Issue by beltschatsar** [Mermade/openapi-lint-vscode#10]
Hi!

Thanks for this extension. I like how it is integrated in visual studio code.

But when I install it, I do not get these working:
 - autocomplete as I type does not work as expected. For example, for /definitions/Acme/properties/field1, for "type" I would expect choices like array, string, ...
 - syntax highlighting when typing string1 instead of string, it does not show error

However, the menus starting with "OpenAPI" are available when typing F1.

Until I realized that the filename is not the one expected by openapi-lint-vscode.

I tried renaming it from open-api.yaml to openapi.yaml. But now it would complain about my v2.0 version (example: first line start with `swagger: "2.0"` and gives `Missing property "openapi"`).

Until I rename it to oas2.yaml. Works like a charm!

Any plan to configure that ?

Thanks

**Comment by MikeRalphson** [comment]
The README documents all the supported filenames for both OpenAPI 2.0 (swagger) and OpenAPI 3.0 intellisense.

The filename matching rules have to be expressed as fixed patterns in the extension's `package.json` so I don't believe it is possible to make them user-configurable, sorry.

**Comment by beltschatsar** [comment]
How about modifying fixed patterns so to be compatible with these file naming scheme ?
 - kebab casing (the one I have here): would add support for theses variants:
  - async-api
  - open-api
  - oas-3
  - oas-2
 - camel casing: would add support for theses variants:
  - asyncApi
  - openApi
  - oas3 (already there)
  - oas2 (already there)

PROs:
 - Would match more use cases (openapi file that is exposed to the web would tend to be named "open-api" to fit URL naming scheme)
CONs:
 - Does not solve all problem: Someone who is in a swagger file (v2), and have this extension just installed would thinks it only works with v3.

Would you accept a PR in that way ?

Thank you

**Comment by MikeRalphson** [comment]
As per the specification, the recommended filename for an OpenAPI v3 document is `openapi.json` or `openapi.yaml`, and `swagger.json` for OpenAPI v2. There is no upper-casing, spaces or hyphens, so I don't think "openapi file that is exposed to the web would tend to be named "open-api" to fit URL naming scheme" really holds up.

So I probably would not merge a PR that added those filename patterns.
