### ISSUE TITLE
Swagger 2.0 in openapi.yml validates against the incorrect spec

### ISSUE THREAD

**Issue by dsample** [Mermade/openapi-lint-vscode#12]
We use libraries which require us to use Swagger 2.0. If I call the file `swagger.yml` it's ok, but if I call the file `openapi.yml` it appears to be validating against a version other than 2.0. We'd prefer to standardise the filename of our specs to `openapi.yml`, but it's causing issues when trying to use this great extension.

I have `swagger: "2.0"` as the first line of the spec, so I'd hope it would be detect this and validate using the correct spec.

**Comment by MikeRalphson** [comment]
Unfortunately the way VS Code implements intellisense using JSON schemas is based on filename patterns, not content. `swagger.json` is the recommended filename for Swagger/OpenAPI 2.0 and `openapi.json` / `openapi.yaml` are the recommended names for OpenAPI 3.x

See the README for all the supported filename patterns.
