### ISSUE TITLE
Enhancement: Validation & linting commands should integrate with the VSCode "problems" panel

### ISSUE THREAD

**Issue by pcgeek86** [Mermade/openapi-lint-vscode#13]
At the moment, when I perform OpenAPI validation or linting against a YAML document, errors are shown in the pop-up dialog in the bottom-right of VSCode. These pop-up notifications should be reserved for important notifications, not general use of the editor.

Instead of displaying errors as pop-ups, the errors / warnings from the OpenAPI extension should be shown in the **Problems** panel in VSCode.

As an example, see the screenshot below, which shows "problems" with a couple of Python files.

<img width="443" alt="Screen Shot 2019-06-20 at 10 17 55 AM" src="https://user-images.githubusercontent.com/466713/59868082-c42f3c80-9344-11e9-8aaf-dd823fcfcffa.png">

Cheers,
Trevor Sullivan

**Comment by MikeRalphson** [comment]
See https://stackoverflow.com/questions/38288511/how-can-i-use-problems-panel-in-my-vscode-extension

**Comment by MikeRalphson** [comment]
Thanks for prompting this. `v1.2.0` has just been released with this functionality.
