### ISSUE TITLE
Configurable names for OAS v3/v2 intellisense for files

### ISSUE THREAD

**Issue by tomkerkhove** [Mermade/openapi-lint-vscode#16]
As of today, all files should follow these naming conventions in order to have IntelliSense:
> - OAS v3 intellisense for files named *openapi.json, *openapi.yaml, *openapi.yml, *oas3.json, *oas3.yaml, *oas3.yml
> - OAS v2 intellisense for files named *swagger.json, *swagger.yaml, *swagger.yml, *oas2.json, *oas2.yaml, *oas2.yml

Would be good to be able to configure the filename patterns.

**Comment by MikeRalphson** [comment]
Unfortunately this does not appear to be possible with the way JSON schema intellisense is configured in VS Code. https://github.com/Mermade/openapi-lint-vscode/issues/10#issuecomment-483952997

**Comment by tomkerkhove** [comment]
No problem @MikeRalphson 	, thanks for checking!
