### ISSUE TITLE
Not working with asyncapi file

### ISSUE THREAD

**Issue by WaleedAshraf** [Mermade/openapi-lint-vscode#19]
It's not working with asyncapi file.
File name: `moch-schema.yaml` (also tried with asyncapi.yaml, same error)
Command used: `OpenAPI Lint`
Version used: 1.2.0

![image](https://user-images.githubusercontent.com/8335457/77184291-e7ec0280-6acf-11ea-92a4-8217e7c1817f.png)

**Comment by MikeRalphson** [comment]
The `OpenAPI Lint` and `Validate` commands only work with OAS 2.0 and 3.0 files.

As per the README, only intellisense (as you type) mode is supported (for now) for AsyncAPI.

**Comment by WaleedAshraf** [comment]
Ok, yes, IntelliSense works.
It's good if we can skip the error (underline) for the asyncapi file until it supported.
