### ISSUE TITLE
Filename prefixes

### ISSUE THREAD

**Issue by mikehardenize** [Mermade/openapi-lint-vscode#2]
Please consider making this extension work with filenames that have prefixes too. E.g, instead of just "openapi.yaml", also work with "anything.openapi.yaml".

**Comment by MikeRalphson** [comment]
Did try this in an earlier release, but will revisit it. Thanks for the suggestion.

**Comment by MikeRalphson** [comment]
Published as `v0.3.1` - thanks again!
