### ISSUE TITLE
Parsing and linting inline OpenAPI documentation

### ISSUE THREAD

**Issue by amitlzkpa** [Mermade/openapi-lint-vscode#28]
Hi

Firstly, thank you for the effort and making this plugin available.
We hope to be able to use this plugin to help with documenting our projects.

We prefer writing inline comments right next to the elements (endpoints, schemas etc.) for our work.
Is there a way to enable the linter to parse and lint the inline comments?

**Comment by MikeRalphson** [comment]
Do you mean some kind of code annotations? I think that would depend on the language and annotation framework, It's something to look into.

**Comment by amitlzkpa** [comment]
Not exactly.
My understanding has been that the linter relies on looking at the extension of the file for linting.
So a .json file which has the OpenAPI documentation work properly.
![image](https://user-images.githubusercontent.com/15354742/109542675-fc2fd200-7a8a-11eb-8d7e-45f0950c1444.png)

However I have my OpenAPI documented defined in the source javascript itself (right above the implementation).
Our team likes that both implementation and documentation are right next to each other and helps us keep the documentation updated.
![image](https://user-images.githubusercontent.com/15354742/109547453-ff2dc100-7a90-11eb-93d5-28fc69d668ef.png)

Is there any way to get the linter to lint the documentation identified under the `@swagger` identifier?

**Comment by MikeRalphson** [comment]
No, unfortunately, linting or validating **fragments** of OpenAPI definitions within comments / code-annotations is out of scope for this project.
