### ISSUE TITLE
Incorrectly Flags Elements

### ISSUE THREAD

**Issue by tqoliver** [Mermade/openapi-lint-vscode#4]
It seems this isn't recognizing properties that are OpenAPI 3.0. Please see the attached screenshot. For the openapi, servers and components properties it says, "Unexpected property openapi" or "Unexpected property servers", etc. do I need to turn on OpenAPI 3.0 in the settings or somewhere? HELP!!

![screen shot 2018-08-22 at 2 04 43 pm](https://user-images.githubusercontent.com/2377889/44482021-4e1f5380-a615-11e8-992c-5250d5beaffc.png)

**Comment by MikeRalphson** [comment]
Intellisense is driven by the filename, so if you use `openapi` in place of `swagger` it should trigger the correct completions and validation.

**Comment by tqoliver** [comment]
Yeah, I discovered that. Thanks for the reply @MikeRalphson
