### ISSUE TITLE
Validate on save

### ISSUE THREAD

**Issue by unlikenesses** [Mermade/openapi-lint-vscode#5]
Currently when I want to validate my `openapi.yaml` file I have to go through the command palette. It would be good if it would do this automatically, either as I type or on save. Is this possible?

**Comment by MikeRalphson** [comment]
Thanks for the suggestion, I'll take a look into what hooks are available.

**Comment by MikeRalphson** [comment]
Simple (schema-based) validation should happen as you type (given that filename), but I'll continue to look into triggering validation on save.

Note to self: https://github.com/Microsoft/vscode/commit/c29f432de5418b84ad6479cfa7c2c8c2d66f0fdc

**Comment by MikeRalphson** [comment]
Experimenting with `vscode.workspace.onWillSaveTextDocument` and `vscode.workspace.onDidSaveTextDocument` but neither appear to be being called...

**Comment by minkir014** [comment]
See this setting that may help you `editor.codeActionsOnSave`.

**Comment by MikeRalphson** [comment]
Thanks for prompting this. `v1.2.0` has just been released with this functionality.
