### ISSUE TITLE
Validation, linting and conversion with external $ref resolution

### ISSUE THREAD

**Issue by MeTaNoV** [Mermade/openapi-lint-vscode#6]
Is there still any development on this plug-in? Is there any way to contribute efficiently?

**Comment by MikeRalphson** [comment]
The plugin is stable, but definitely not abandoned. Help would be appreciated with issue #5 if you're familiar with VSCode extension development. There are also some planned features in the `README`.

Alternatively, if you have other ideas for improvements, do let me know here.

**Comment by MikeRalphson** [comment]
Version `1.0.0` has been released with the external `$ref` resolution features. Thanks for prodding me to get this done!
