### ISSUE TITLE
OpenApi 3.x validation error when "servers" object is present

### ISSUE THREAD

**Issue by hecsalazar** [Mermade/openapi-lint-vscode#9]
When adding the servers section with a basic object with only the url mandatory property the validation fails stating that the url property is expected.
This can be reproduced with the OpenApi 3.x Jamal samples

**Comment by hecsalazar** [comment]
Sample file to reproduce, if the "servers" section is commented validation passes

`openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string`

**Comment by MikeRalphson** [comment]
Hmm, I can't see any errors with your example file either with the intellisense or the `OpenAPI Validate`  command. If you use the `OpenAPI Lint` command it complains about the `servers.url` property containing `example.com`, but that is expected.

Please can you let me know the filename you are using and the version of the extension you have installed?

**Comment by hecsalazar** [comment]
filename: vscode_lint_sample.yaml
extension version: openapi-lint 1.0.2

Here's a sample capture of failure of "OpenApi Validate" with the above example

![vscode_openapi_error](https://user-images.githubusercontent.com/10752909/55341041-e7e49400-5473-11e9-82b5-f5cbfb8a6acc.gif)

**Comment by MikeRalphson** [comment]
Sorry, I still can't reproduce this, so I can only assume there's an interaction with another vscode extension.

**Comment by hecsalazar** [comment]
Tried disabling other extensions related to open api and swagger, I get the same result:

![image](https://user-images.githubusercontent.com/10752909/64030940-82293080-cb15-11e9-8395-54492e0a6e05.png)
![image](https://user-images.githubusercontent.com/10752909/64030957-8a816b80-cb15-11e9-8929-3fa5666d9acc.png)
![image](https://user-images.githubusercontent.com/10752909/64030951-87867b00-cb15-11e9-9bce-d921730f9fb2.png)

**Comment by hecsalazar** [comment]
Here's my full list of extensions:
```
code --list-extensions

adashen.vscode-tomcat
AlanWalk.markdown-toc
Arjun.swagger-viewer
bat67.markdown-extension-pack
bierner.markdown-emoji
bierner.markdown-preview-github-styles
bungcip.better-toml
cstuder.gitlab-ci-validator
darkriszty.markdown-table-prettify
DavidAnson.vscode-markdownlint
eriklynd.json-tools
fatihacet.gitlab-workflow
faustinoaq.javac-linter
foxundermoon.shell-format
fwcd.kotlin
goessner.mdmath
ipedrazas.kubernetes-snippets
mathiasfrohlich.Kotlin
mauve.terraform
mermade.openapi-lint
momoto.binary-viewer
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-vscode-remote.remote-wsl
ms-vscode.cpptools
ms-vscode.Go
ms-vscode.powershell
ms-vsliveshare.vsliveshare
philosowaffle.openapi-designer
Pivotal.vscode-spring-boot
redhat.java
redhat.vscode-yaml
shd101wyy.markdown-preview-enhanced
shengchen.vscode-checkstyle
sidneys1.gitconfig
slevesque.vscode-hexdump
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscjava.vscode-spring-initializr
yzane.markdown-pdf
yzhang.markdown-all-in-one
zoellner.openapi-preview
zxh404.vscode-proto3
```

**Comment by MikeRalphson** [comment]
@dariusj18 you reacted with a :+1: to the original issue, are you also running any of @hecsalazar 's extensions?

**Comment by dariusj18** [comment]
Here's my extension list

```adamhartford.vscode-base64
adisreyaj.swagger-snippets
alefragnani.Bookmarks
alefragnani.project-manager
Arjun.swagger-viewer
bbenoist.vagrant
bmarkovic.haproxy
bmewburn.vscode-intelephense-client
christian-kohler.npm-intellisense
CoenraadS.bracket-pair-colorizer
crasnam.elasticdeveloper
cssho.vscode-svgviewer
dakara.dakara-foldplus
donjayamanne.githistory
DotJoshJohnson.xml
dssiqueira.drupal-8-snippets
eamodio.gitlens
EditorConfig.EditorConfig
eg2.vscode-npm-script
esbenp.prettier-vscode
felixfbecker.php-debug
fknop.vscode-npm
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
hdg.live-html-previewer
ikappas.composer
ikappas.phpcs
jakelucas.code-select-until
jmlv.MeteorSnippets
johnpapa.vscode-peacock
KamasamaK.vscode-cfml
karigari.chat
lindraupe.aw-watcher-vscode
marcostazi.VS-code-drupal
marcostazi.VS-code-vagrantfile
mechatroner.rainbow-csv
mermade.openapi-lint
mikestead.dotenv
mkloubert.vscode-deploy-reloaded
mrmlnc.vscode-apache
mrmlnc.vscode-autoprefixer
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-mssql.mssql
ms-python.python
ms-vscode-remote.remote-wsl
ms-vscode.powershell
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
ms-vsliveshare.vsliveshare-pack
msjsdiag.debugger-for-chrome
mtxr.sqltools
neilbrayfield.php-docblocker
oderwat.indent-rainbow
onecentlin.laravel-blade
philosowaffle.openapi-designer
ramonitor.meteorhelper
RandomChance.logstash
redhat.java
redhat.vscode-yaml
ria.elastic
ritwickdey.LiveServer
ryannaddy.laravel-artisan
santigarcor.phpunit-extended
slevesque.vscode-autohotkey
spywhere.guides
streetsidesoftware.code-spell-checker
thomas-baumgaertner.vcl
tomoki1207.vscode-input-sequence
Tyriar.lorem-ipsum
vscode-icons-team.vscode-icons
vuhrmeister.vscode-meteor
whatwedo.twig```

**Comment by MikeRalphson** [comment]
Common extensions are:

```
Arjun.swagger-viewer
ms-azuretools.vscode-docker
ms-kubernetes-tools.vscode-kubernetes-tools
ms-python.python
ms-vscode.powershell
ms-vscode-remote.remote-wsl
ms-vsliveshare.vsliveshare
philosowaffle.openapi-designer
redhat.java
```

Ignoring `redhat.vscode-yaml` and `mermade.openapi-lint`.

**Comment by MikeRalphson** [comment]
Something (presumably an extension) definitely appears to be polluting the `Array` prototype.

**Comment by dariusj18** [comment]
Seems to be `ms-kubernetes-tools.vscode-kubernetes-tools`

**Comment by hecsalazar** [comment]
> Seems to be `ms-kubernetes-tools.vscode-kubernetes-tools`

I confirm, when disabling that extension It the validation works, I reenabled and the error appears.

@MikeRalphson I suggest to debug to confirm if it's an issue in Microsoft extension and report to them or mermade itself to move forward on a fix

**Comment by MikeRalphson** [comment]
Please refer / subscribe to https://github.com/Azure/vscode-kubernetes-tools/issues/613

**Comment by MikeRalphson** [comment]
Added some forced pollution cleanup code in `mermade.openapi-lint@1.0.4`

It would be great to get confirmation that this resolves the issue.

**Comment by hecsalazar** [comment]
I confirmed it works with microsoft kubernetes extension enabled.

Important tip: you need to update and restart vscode, in my first try I
just updated just the extension and didn't work.

**Comment by MikeRalphson** [comment]
Thanks for everyone's help in tracking down the cause of this behaviour.
